# Generated by Django 3.1.4 on 2020-12-22 16:39

from django.db import migrations, models
import django.db.models.deletion
import shortuuidfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='help')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='organizations')),
                ('circular_icon', models.ImageField(blank=True, null=True, upload_to='organizations/circle')),
                ('short_description', models.TextField(max_length=300)),
                ('quote', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('name', models.CharField(max_length=20)),
                ('short_description', models.TextField(max_length=900)),
                ('recomedations', models.TextField(max_length=900)),
                ('category', models.CharField(max_length=11)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_points', to='maps.organization')),
                ('photos', models.ManyToManyField(to='maps.HelpPhoto')),
            ],
        ),
    ]
