# Generated by Django 3.1.4 on 2020-12-16 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RenameModel(
            old_name='Points',
            new_name='Point',
        ),
        migrations.CreateModel(
            name='Help',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('longitude', models.DecimalField(decimal_places=3, max_digits=5)),
                ('name', models.CharField(max_length=60)),
                ('short_description', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=2000)),
                ('category', models.CharField(max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_points', to='maps.organization')),
            ],
        ),
    ]
