# Generated by Django 3.1.4 on 2020-12-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
        migrations.AlterField(
            model_name='help',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=6),
        ),
    ]
