# Generated by Django 3.1.4 on 2020-12-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20201222_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
