# Generated by Django 3.1.4 on 2020-12-16 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20201216_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='description',
            field=models.TextField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='help',
            name='short_description',
            field=models.TextField(max_length=900),
        ),
    ]
