# Generated by Django 3.1.4 on 2020-12-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_organization_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
