# Generated by Django 3.1.4 on 2020-12-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20201224_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='temporal_code',
            field=models.CharField(default='XXX-000-XXX', max_length=11),
        ),
    ]
