# Generated by Django 3.1.4 on 2020-12-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20201217_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.CharField(max_length=11),
        ),
    ]
