# Generated by Django 3.1.4 on 2020-12-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_help_temporal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='points_for_completed',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='help',
            name='temporal_code',
            field=models.CharField(max_length=11),
        ),
    ]
