# Generated by Django 3.1.4 on 2020-12-18 01:55

from django.db import migrations, models
import shortuuidfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20201217_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='uuid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.AlterField(
            model_name='help',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
