# Generated by Django 3.1.4 on 2020-12-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20201217_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='circular_icon',
            field=models.ImageField(blank=True, null=True, upload_to='maps/static/maps/images/organizations/circular'),
        ),
    ]
