# Generated by Django 3.1.4 on 2020-12-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_organization_circular_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='circular_icon',
            field=models.ImageField(blank=True, null=True, upload_to='maps/images/organizations/circular'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='maps/images/organizations'),
        ),
    ]
