# Generated by Django 3.1.4 on 2021-01-19 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20210119_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='contact_phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el codigo del pais. Ej: +573023986488. 15 Digitos permitidos', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el codigo del pais. Ej: +573023986488. 15 Digitos permitidos', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
