# Generated by Django 3.1.5 on 2021-01-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20210126_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='responses',
            field=models.ManyToManyField(related_name='_comment_responses_+', to='maps.Comment'),
        ),
    ]
