# Generated by Django 3.1.5 on 2021-01-26 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0013_comment_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='responses',
            field=models.ManyToManyField(blank=True, null=True, related_name='_comment_responses_+', to='maps.Comment'),
        ),
    ]
