# Generated by Django 3.1.4 on 2020-12-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0014_auto_20201218_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='quote',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='short_description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='help',
            name='recomedations',
            field=models.TextField(default='Lorem ipsum dolor sit amet consectetur adipiscing elit vehicula sociosqu ut, nec varius feugiat nostra ridiculus ad facilisi nulla curae, interdum congue eros vulputate nisl sagittis praesent eu et. Nam viverra sapien augue dignissim elementum nostra, class hac pellentesque duis condimentum arcu, congue habitasse eros potenti gravida. Auctor feugiat consequat interdum ultricies volutpat molestie maecenas justo, conubia tortor sagittis felis luctus cum mauris, fames turpis donec sed blandit malesuada hac. Velit vitae iaculis ligula malesuada ullamcorper gravida consequat erat felis sed integer.', max_length=900),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='circular_icon',
            field=models.ImageField(default='maps/image-png', upload_to='maps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(upload_to='maps'),
        ),
    ]
