# Generated by Django 3.1.4 on 2020-12-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0016_auto_20201218_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='circular_icon',
            field=models.ImageField(upload_to='organizations/circle'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(upload_to='organizations'),
        ),
    ]
