# Generated by Django 3.1.4 on 2020-12-18 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_auto_20201218_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='circular_icon',
            field=models.ImageField(null=True, upload_to='organizations/circle'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(null=True, upload_to='organizations'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='quote',
            field=models.CharField(default='Lorem ipsum', max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='short_description',
            field=models.TextField(default='lorem', max_length=300),
            preserve_default=False,
        ),
    ]
