# Generated by Django 3.1.5 on 2021-01-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0017_auto_20210128_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='organization',
        ),
    ]
