# Generated by Django 3.1.5 on 2021-01-29 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_remove_help_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='comments',
        ),
    ]
