# Generated by Django 3.1.4 on 2020-12-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0018_auto_20201218_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='circular_icon',
            field=models.ImageField(blank=True, null=True, upload_to='organizations/circle'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='organizations'),
        ),
    ]
