# Generated by Django 3.1.4 on 2020-12-18 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0019_auto_20201218_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='help')),
            ],
        ),
        migrations.AddField(
            model_name='help',
            name='photos',
            field=models.ManyToManyField(to='maps.HelpPhoto'),
        ),
    ]
