# Generated by Django 3.1.5 on 2021-01-29 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
        ('maps', '0019_remove_help_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='comments',
            field=models.ManyToManyField(to='maps.Comment'),
        ),
        migrations.AddField(
            model_name='help',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='help_points', to='info.organization'),
            preserve_default=False,
        ),
    ]
