# Generated by Django 3.1.5 on 2021-01-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0021_auto_20210128_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='comments',
            field=models.ManyToManyField(blank=True, to='maps.Comment'),
        ),
    ]
