# Generated by Django 3.1.5 on 2021-01-29 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0022_auto_20210128_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=10),
        ),
        migrations.AlterField(
            model_name='help',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
