# Generated by Django 3.1.5 on 2021-02-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0023_auto_20210129_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='style',
            field=models.CharField(choices=[('D', 'Donar'), ('V', 'Voluntariado')], default='D', max_length=1),
        ),
    ]
