# Generated by Django 3.1.5 on 2021-02-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0024_help_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
