# Generated by Django 3.1.5 on 2021-02-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0028_auto_20210204_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.CharField(choices=[('DAl', 'Alimentos'), ('DBb', 'Artículos para Bebés'), ('DRp', 'Ropa'), ('DCn', 'Cocina'), ('DCl', 'Colchones y Frazadas'), ('DMu', 'Muebles'), ('DTc', 'Tecnología'), ('DRc', 'Recreación'), ('DLb', 'Libros'), ('DSl', 'Salud'), ('DOt', 'Otros'), ('VNi', 'Ayuda con Niños'), ('VAd', 'Adultos Mayores'), ('VFa', 'Familia'), ('VCo', 'Comedores'), ('VEd', 'Educacion'), ('VSl', 'Salud'), ('VDs', 'Personas con Discapacidad'), ('VIn', 'Indigencia'), ('VRs', 'Reinserción Social'), ('VPr', 'Profesional'), ('VAm', 'Medio Ambiente'), ('VOt', 'Otros Voluntariados')], default='DAl', max_length=3),
        ),
    ]
