# Generated by Django 3.1.5 on 2021-02-04 17:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0029_auto_20210204_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='sub_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DLchPol', 'Leche en Polvo'), ('DLchEnt', 'Leche Entera'), ('DAlNoPe', 'No perecederos'), ('DAlPere', 'Perecederos'), ('DBbPana', 'Pañales'), ('DBbOtro', 'Otros (Cunas, etc)'), ('DRpNino', 'Para Niños'), ('DRpJove', 'Para Jóvenes'), ('DRpAdul', 'Para Adultos'), ('DCnArti', 'Artículos de Cocina'), ('DCnElec', 'Electrodomésticos'), ('DClColc', 'Colchones'), ('DClFraz', 'Frazadas'), ('DClSaba', 'Sábanas'), ('DMuBiAr', 'Bibliotecas y Armarios'), ('DMuCaCt', 'Camas y Catres'), ('DMuMeSi', 'Mesas y Sillas'), ('DMuOtro', 'Otros Muebles'), ('DTcCamr', 'Camaras de fotos/videos'), ('DTcComp', 'Computadoras'), ('DTcImpr', 'Impresoras'), ('DTcOtro', 'Otra Tecnologia'), ('DRcDepo', 'Articulos Deportivos'), ('DRcMusi', 'Instrumentos Musicales'), ('DRcJugt', 'Juguetes'), ('DRcArte', 'Material Artisticos'), ('DLbEscl', 'Escolares'), ('DLbInft', 'Infantiles'), ('DLbOtro', 'Otros Libros'), ('DSlMedi', 'Medicamentos'), ('DSlPrim', 'Primeros Auxilios'), ('DSlSang', 'Sangre'), ('DSlOtro', 'Otros Equipos Medicos'), ('DOtLimp', 'Limpieza'), ('DOtCstr', 'Material de Construccion'), ('DOtPint', 'Pintura'), ('DOtPelo', 'Cabello'), ('DotOtro', 'Otro Otro'), ('VNiNino', 'Niños'), ('VNiAdol', 'Adolecentes'), ('VniEmba', 'Embarazadas'), ('VAdAdAd', 'Personas Mayores'), ('VFaAsSo', 'Asistencia Social'), ('VFVivi', 'Vivienda'), ('VCoNino', 'Con Niños'), ('VCoAdul', 'Con Adultos'), ('VEdApoy', 'Apoyo Escolar'), ('VEdTall', 'Talleres'), ('VEdCurs', 'Cursos'), ('VSlAdic', 'Adicciones'), ('VSlEnfe', 'Enfermedades'), ('VSlOtro', 'Otro Salud'), ('VDsNino', 'Niños Discapacitados'), ('VDsAdul', 'Adultos Discapacitados'), ('VInInIn', 'Indigencia'), ('VRsCarc', 'Carceles'), ('VRsOtro', 'Otros Centros'), ('VPrAdmi', 'Administracion'), ('VPrComu', 'Comunicacion'), ('VPrDere', 'Derecho'), ('VPrDise', 'Diseño'), ('VPrDoce', 'Docencia'), ('VPrMedi', 'Medicos'), ('VPrPsic', 'Psicologia'), ('VPrTecn', 'Tecnologia'), ('VPrCoci', 'Cocinero'), ('VOtAnim', 'Animales'), ('VOtOtro', 'Otros Voluntariados')], max_length=32),
        ),
    ]
