# Generated by Django 3.1.5 on 2021-02-04 17:48

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0030_auto_20210204_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.CharField(choices=[('DAl', 'Alimentos'), ('DBb', 'Artículos para Bebés'), ('DRp', 'Ropa'), ('DCn', 'Cocina'), ('DCl', 'Colchones y Frazadas'), ('DMu', 'Muebles'), ('DTc', 'Tecnología'), ('DRc', 'Recreación'), ('DLb', 'Libros'), ('DSl', 'Salud'), ('DOt', 'Otros'), ('VNi', 'Ayuda con Niños'), ('VAd', 'Adultos Mayores'), ('VFa', 'Familia'), ('VCo', 'Comedores'), ('VEd', 'Educacion'), ('VSl', 'Salud'), ('VDs', 'Personas con Discapacidad'), ('VIn', 'Indigencia'), ('VRs', 'Reinserción Social'), ('VPr', 'Profesional'), ('VOt', 'Otros Voluntariados')], default='DAl', max_length=3),
        ),
        migrations.AlterField(
            model_name='help',
            name='sub_category',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('DLchPol', 'Leche en Polvo'), ('DLchEnt', 'Leche Entera'), ('DAlNoPe', 'No perecederos'), ('DAlPere', 'Perecederos'), ('DBbPana', 'Pañales'), ('DBbOtro', 'Otros (Cunas, etc)'), ('DRpNino', 'Para Niños'), ('DRpJove', 'Para Jóvenes'), ('DRpAdul', 'Para Adultos'), ('DCnArti', 'Artículos de Cocina'), ('DCnElec', 'Electrodomésticos'), ('DClColc', 'Colchones'), ('DClFraz', 'Frazadas'), ('DClSaba', 'Sábanas'), ('DMuBiAr', 'Bibliotecas y Armarios'), ('DMuCaCt', 'Camas y Catres'), ('DMuMeSi', 'Mesas y Sillas'), ('DMuOtro', 'Otros Muebles'), ('DTcCamr', 'Camaras de fotos/videos'), ('DTcComp', 'Computadoras'), ('DTcImpr', 'Impresoras'), ('DTcOtro', 'Otra Tecnologia'), ('DRcDepo', 'Articulos Deportivos'), ('DRcMusi', 'Instrumentos Musicales'), ('DRcJugt', 'Juguetes'), ('DRcArte', 'Material Artisticos'), ('DLbEscl', 'Escolares'), ('DLbInft', 'Infantiles'), ('DLbOtro', 'Otros Libros'), ('DSlMedi', 'Medicamentos'), ('DSlPrim', 'Primeros Auxilios'), ('DSlSang', 'Sangre'), ('DSlOtro', 'Otros Equipos Medicos'), ('DOtLimp', 'Limpieza'), ('DOtCstr', 'Material de Construccion'), ('DOtPint', 'Pintura'), ('DOtPelo', 'Cabello'), ('DotOtro', 'Otro Otro'), ('VNiNino', 'Niños'), ('VNiAdol', 'Adolecentes'), ('VniEmba', 'Embarazadas'), ('VAdAdAd', 'Personas Mayores'), ('VFaAsSo', 'Asistencia Social'), ('VFVivi', 'Vivienda'), ('VCoNino', 'Con Niños'), ('VCoAdul', 'Con Adultos'), ('VEdApoy', 'Apoyo Escolar'), ('VEdTall', 'Talleres'), ('VEdCurs', 'Cursos'), ('VSlAdic', 'Adicciones'), ('VSlEnfe', 'Enfermedades'), ('VSlOtro', 'Otro Salud'), ('VDsNino', 'Niños Discapacitados'), ('VDsAdul', 'Adultos Discapacitados'), ('VInInIn', 'Indigencia'), ('VRsCarc', 'Carceles'), ('VRsOtro', 'Otros Centros'), ('VPrAdmi', 'Administracion'), ('VPrComu', 'Comunicacion'), ('VPrDere', 'Derecho'), ('VPrDise', 'Diseño'), ('VPrDoce', 'Docencia'), ('VPrMedi', 'Medicos'), ('VPrPsic', 'Psicologia'), ('VPrTecn', 'Tecnologia'), ('VPrCoci', 'Cocinero'), ('VOtAnim', 'Animales'), ('VotAmbi', 'Medio Ambiente'), ('VOtOtro', 'Otros Voluntariados')], max_length=32),
        ),
    ]
