# Generated by Django 3.1.5 on 2021-02-06 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0033_auto_20210205_2143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='codigo',
            new_name='code',
        ),
    ]
