# Generated by Django 3.1.5 on 2021-02-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0034_auto_20210205_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='help',
            name='category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('sub_categories', models.ManyToManyField(to='maps.SubCategory')),
            ],
        ),
        migrations.AddField(
            model_name='help',
            name='category',
            field=models.ManyToManyField(to='maps.Category'),
        ),
    ]
