# Generated by Django 3.1.5 on 2021-02-06 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0035_auto_20210205_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sub_categories',
            field=models.ManyToManyField(blank=True, to='maps.SubCategory'),
        ),
    ]
