# Generated by Django 3.1.5 on 2021-02-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0036_auto_20210205_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.RemoveField(
            model_name='help',
            name='category',
        ),
        migrations.AddField(
            model_name='help',
            name='category',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.RESTRICT, to='maps.category'),
            preserve_default=False,
        ),
    ]
