# Generated by Django 3.1.5 on 2021-02-06 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0038_auto_20210206_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='helps', to='maps.category'),
        ),
        migrations.AlterField(
            model_name='help',
            name='sub_category',
            field=models.ManyToManyField(related_name='helps', to='maps.SubCategory'),
        ),
    ]
