# Generated by Django 3.1.5 on 2021-03-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0041_help_data_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
