# Generated by Django 3.1.4 on 2020-12-24 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_organization_points'),
        ('login', '0003_auto_20201223_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visited',
            field=models.ManyToManyField(blank=True, null=True, related_name='persons_visited', to='maps.Help'),
        ),
    ]
