# Generated by Django 3.1.4 on 2021-01-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20210104_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='random_number',
        ),
        migrations.AddField(
            model_name='user',
            name='can_change',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
