# Generated by Django 3.1.4 on 2021-01-05 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_auto_20210104_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_forgot',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='random_string',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
