# Generated by Django 3.1.5 on 2021-02-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_auto_20210129_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='visited',
        ),
    ]
