# Generated by Django 3.1.5 on 2021-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0029_auto_20210204_1200'),
        ('login', '0011_remove_user_visited'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visited',
            field=models.ManyToManyField(blank=True, null=True, related_name='persons_visited', to='maps.Help'),
        ),
    ]
