# Generated by Django 3.1.5 on 2021-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0040_category_color'),
        ('login', '0012_user_visited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='visited',
            field=models.ManyToManyField(blank=True, related_name='persons_visited', to='maps.Help'),
        ),
    ]
