# Generated by Django 3.1.5 on 2021-01-29 02:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el codigo del pais. Ej: +573023986488. 15 Digitos permitidos', regex='^\\+?1?\\d{9,15}$')])),
                ('contact_name', models.CharField(blank=True, max_length=30)),
                ('contact_phone_number', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='El numero de telefono debe tener el codigo del pais. Ej: +573023986488. 15 Digitos permitidos', regex='^\\+?1?\\d{9,15}$')])),
                ('image', models.ImageField(blank=True, null=True, upload_to='organizations')),
                ('circular_icon', models.ImageField(blank=True, null=True, upload_to='organizations/circle')),
                ('short_description', models.TextField(max_length=300)),
                ('quote', models.CharField(max_length=60)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organization', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
