# Generated by Django 3.1.5 on 2021-03-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_auto_20210310_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='see',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
