# Generated by Django 3.1.5 on 2021-02-08 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_or_user', models.CharField(choices=[('U', 'User'), ('O', 'Organization')], max_length=1)),
                ('name_of_reported', models.CharField(max_length=64)),
                ('category_of_problem', models.CharField(choices=[('IfEn', 'Informacion Engañosa'), ('MaCa', 'Mal Categorizado'), ('CoSe', 'Contenido Sexual'), ('CoOf', 'Contenido Ofensivo'), ('CoPo', 'Contenido Politico'), ('AcIl', 'Actividades Ilegales'), ('Ment', 'Mentiras'), ('MaUb', 'Mala Ubicacion'), ('MaCo', 'No dan codigo'), ('Bane', 'Me bannearon sin motivo'), ('MaIn', 'Falta de informacion o informacion no clara'), ('Otro', 'Otro Motivo')], max_length=4)),
                ('decription_of_the_problem', models.TextField()),
                ('user_that_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
