# Generated by Django 3.1.5 on 2021-02-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='organization_or_user',
            field=models.CharField(choices=[('U', 'Usuario'), ('O', 'Organización')], max_length=1),
        ),
    ]
