# Generated by Django 3.1.5 on 2021-03-04 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0041_help_data_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('control', '0002_auto_20210227_1017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aproved', models.BooleanField()),
                ('help_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.help')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
