# Generated by Django 3.1.5 on 2021-03-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='points_earned',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
