# Generated by Django 3.1.5 on 2021-03-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_notification_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='discarted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
