# Generated by Django 3.1.5 on 2021-03-04 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0006_notification_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='aproved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='discarted',
            field=models.BooleanField(default=False),
        ),
    ]
